import { useState } from "react";
import { Printer } from "lucide-react";
import { Button } from "@/components/ui/button";
import {
  Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger, DialogFooter,
} from "@/components/ui/dialog";
import { toast } from "sonner";

type Row = { label: string; value: string };

export function PrintPreview({
  docType, number, customer, date, dueDate, lines, totals,
}: {
  docType: "Quotation" | "Purchase Order" | "Customer Invoice" | "Service Record";
  number: string; customer: string; date: string; dueDate?: string;
  lines: { name: string; qty: number; unitPrice: number }[];
  totals?: Row[];
}) {
  const [open, setOpen] = useState(false);
  const subtotal = lines.reduce((s, l) => s + l.qty * l.unitPrice, 0);
  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <DialogTrigger asChild>
        <Button size="sm" variant="outline"><Printer className="w-4 h-4 mr-1.5" />Print preview</Button>
      </DialogTrigger>
      <DialogContent className="max-w-2xl">
        <DialogHeader>
          <DialogTitle>{docType} Preview — {number}</DialogTitle>
        </DialogHeader>
        <div className="border rounded-md p-6 bg-white text-foreground space-y-4 text-sm">
          <div className="flex justify-between items-start">
            <div>
              <div className="font-display text-lg font-semibold">MTO Business OS</div>
              <div className="text-xs text-muted-foreground">Private demo • Mock document</div>
            </div>
            <div className="text-right">
              <div className="font-semibold">{docType}</div>
              <div className="text-xs">{number}</div>
              <div className="text-xs text-muted-foreground">Date: {date}</div>
              {dueDate && <div className="text-xs text-muted-foreground">Due: {dueDate}</div>}
            </div>
          </div>
          <div className="border-t pt-3">
            <div className="text-xs text-muted-foreground">Bill To</div>
            <div className="font-medium">{customer}</div>
          </div>
          <table className="w-full text-sm">
            <thead><tr className="border-b text-left text-xs text-muted-foreground">
              <th className="py-1">Item</th><th className="py-1 text-right">Qty</th>
              <th className="py-1 text-right">Unit</th><th className="py-1 text-right">Amount</th>
            </tr></thead>
            <tbody>
              {lines.map((l, i) => (
                <tr key={i} className="border-b last:border-0">
                  <td className="py-1.5">{l.name}</td>
                  <td className="py-1.5 text-right">{l.qty}</td>
                  <td className="py-1.5 text-right">{l.unitPrice.toLocaleString()}</td>
                  <td className="py-1.5 text-right">{(l.qty * l.unitPrice).toLocaleString()}</td>
                </tr>
              ))}
            </tbody>
          </table>
          <div className="flex justify-end">
            <div className="w-56 space-y-1">
              <div className="flex justify-between text-sm"><span>Subtotal</span><span>{subtotal.toLocaleString()}</span></div>
              {totals?.map((t) => (
                <div key={t.label} className="flex justify-between text-sm"><span>{t.label}</span><span>{t.value}</span></div>
              ))}
            </div>
          </div>
          <div className="text-[11px] text-muted-foreground border-t pt-3">
            This is a mock preview generated by the demo. No real document is produced.
          </div>
        </div>
        <DialogFooter>
          <Button variant="outline" onClick={() => toast.info("พิมพ์ (เดโม)")}>
            <Printer className="w-4 h-4 mr-1.5" />Print
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
